### PR TITLE
Use wakatime plugin insead of using `extraPlugins`

### PR DESCRIPTION
**Pull request by rollf**
This could be merged once Neve is updated to use a nixvim verion that is includes this [PR](https://github.com/nix-community/nixvim/pull/1652). Untested.

Thanks for the great work, I started using Neve using last week and the experience has been fantastic so far.

### CODE REVIEW

**Comment by rollf** [comment]
Mh, I changed the target branch from `main` to `dev`. However, I started branching from `main` in the first place. Not sure what is correct here.

**Comment by redyf** [comment]
> This could be merged once Neve is updated to use a nixvim verion that is includes this [PR](https://github.com/nix-community/nixvim/pull/1652). Untested.
> 
> Thanks for the great work, I started using Neve using last week and the experience has been fantastic so far.

Hello rollf, sorry for the late reply. I'm glad you liked it! I'll update Neve to a newer nixvim version.

**Comment by redyf** [comment]
> Mh, I changed the target branch from `main` to `dev`. However, I started branching from `main` in the first place. Not sure what is correct here.

First of all thanks for the contribution, but you'll need to fix those commits as they contain some stuff that has been merged already.

**Comment by rollf** [comment]
Okay, I rebased my branch on `dev`. Now, there is only a single commit left. I hope I understood you correctly.

**Comment by redyf** [comment]
> Okay, I rebased my branch on `dev`. Now, there is only a single commit left. I hope I understood you correctly.

It was exactly that, thanks again for your contribution :100:

**Pull request merged**
